[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config

solc_version = '0.8.26'
optimize = true
optimizer-runs = 1
